import { Link } from 'react-router-dom';
import React from 'react';
import { DateTimeFromTimestamp } from '../../../toolbox/timestamp';
import Box from '../../../toolbox/box';
import Feedback from '../../../toolbox/feedback/feedback';
import LiskAmount from '../../../shared/liskAmount';
import PageLayout from '../../../toolbox/pageLayout';
import CopyToClipboard from '../../../toolbox/copyToClipboard';
import routes from '../../../../constants/routes';
import styles from './blockDetails.css';

const BlockDetails = ({ t, blockDetails }) => (
  <PageLayout>
    <Box isLoading={blockDetails.isLoading} width="full">
      <Box.Header>
        <h1>{t('Block details')}</h1>
      </Box.Header>
      {
        blockDetails.error
          ? (
            <Box.Content>
              <Feedback status="error" show>{t('Failed to load block details.')}</Feedback>
            </Box.Content>
          )
          : (
            <React.Fragment>
              <div>
                <Box.Row>
                  <div className={styles.dataContainer}>
                    <label>{t('Block ID')}</label>
                    <span>
                      <CopyToClipboard value={blockDetails.data.id} />
                    </span>
                  </div>

                  <div className={styles.dataContainer}>
                    <label>{t('Height')}</label>
                    <span>
                      <CopyToClipboard value={blockDetails.data.height} />
                    </span>
                  </div>

                  <div className={styles.dataContainer}>
                    <label>{t('Version')}</label>
                    <span>{blockDetails.data.version}</span>
                  </div>

                  <div className={styles.dataContainer}>
                    <label>{t('Confirmations')}</label>
                    <span>{blockDetails.data.confirmations}</span>
                  </div>

                  <div className={styles.dataContainer}>
                    <label>{t('Reward')}</label>
                    <span>
                      <LiskAmount val={blockDetails.data.reward} token={t('LSK')} />
                    </span>
                  </div>
                </Box.Row>

                <Box.Row>
                  <div className={styles.dataContainer}>
                    <label>{t('Total fee')}</label>
                    <span>
                      <LiskAmount val={blockDetails.data.totalFee} token={t('LSK')} />
                    </span>
                  </div>

                  <div className={styles.dataContainer}>
                    <label>{t('Total forged')}</label>
                    <span>
                      <LiskAmount val={blockDetails.data.totalForged} token={t('LSK')} />
                    </span>
                  </div>

                  <div className={styles.dataContainer}>
                    <label>{t('Total amount')}</label>
                    <span>
                      <LiskAmount val={blockDetails.data.totalAmount} token={t('LSK')} />
                    </span>
                  </div>

                  <div className={styles.dataContainer}>
                    <label>{t('Date')}</label>
                    <span>
                      <DateTimeFromTimestamp time={blockDetails.data.timestamp * 1000} token="BTC" />
                    </span>
                  </div>

                  <div className={styles.dataContainer}>
                    <label>{t('Generated by')}</label>
                    <span>
                      <Link to={`${routes.accounts.path}/${blockDetails.data.generatorAddress}`}>
                        {blockDetails.data.generatorUsername}
                      </Link>
                    </span>
                  </div>
                </Box.Row>
              </div>
            </React.Fragment>
          )
      }
    </Box>
  </PageLayout>
);

export default BlockDetails;
