import { withTranslation } from 'react-i18next';
import React from 'react';
import FilterDropdownButton from '../../../shared/filterDropdownButton';

const BlockFilterDropdown = ({ t, applyFilters }) => {
  const fields = [{
    label: t('Date'),
    name: 'date',
    type: 'date-range',
  }, {
    label: t('Height'),
    placeholder: t('i.e. 10169746'),
    name: 'height',
    type: 'text',
  }, {
    label: t('Generated by'),
    placeholder: t('i.e. shinekami'),
    name: 'address',
    type: 'text',
  }];
  const filters = {
    dateFrom: '',
    dateTo: '',
    height: '',
    address: '',
  };

  const props = { fields, filters, applyFilters };

  return <FilterDropdownButton {...props} />;
};

export default withTranslation()(BlockFilterDropdown);
