import { withTranslation } from 'react-i18next';
import React from 'react';
import FilterDropdownButton from '../../../shared/filterDropdownButton';

const BlockFilterDropdown = ({ t, filters, applyFilters }) => {
  const fields = [{
    label: t('Date'),
    name: 'date',
    type: 'date-range',
  }, {
    label: t('Height'),
    placeholder: t('i.e. {{value}}', { value: 10169746 }),
    name: 'height',
    type: 'text',
    valueFormatter: value => value.replace(/[^\d]/g, ''),
  }, {
    label: t('Generated by'),
    placeholder: t('i.e. {{value}}', { value: 'shinekami' }),
    name: 'address',
    type: 'text',
  }];

  const props = { fields, filters, applyFilters };

  return <FilterDropdownButton {...props} />;
};

export default withTranslation()(BlockFilterDropdown);
