import grid from 'flexboxgrid/dist/flexboxgrid.css';

export default (changeSort, t) => ([
  {
    title: t('Height'),
    classList: `${grid['col-md-1']}`,
    sort: {
      fn: changeSort,
      key: 'height',
    },
  },
  {
    title: t('Date'),
    classList: `${grid['col-md-2']}`,
  },
  {
    title: t('Transactions'),
    classList: `${grid['col-md-3']}`,
  },
  {
    title: t('Generated by'),
    classList: `${grid['col-md-2']}`,
  },
  {
    title: t('Amount'),
    classList: `${grid['col-md-2']}`,
  },
  {
    title: t('Forged'),
    classList: `${grid['col-md-2']}`,
  },
]);
