const maxMessageLength = 64;
const MIN_ACCOUNT_BALANCE = 5000000;
const MIN_FEE_PER_BYTE = 1000;

const DEFAULT_NUMBER_OF_SIGNATURES = 1;
const DEFAULT_SIGNATURE_BYTE_SIZE = 64;

const STAKE_AMOUNT_STEP = 1e9;

export {
  maxMessageLength,
  MIN_ACCOUNT_BALANCE,
  MIN_FEE_PER_BYTE,
  DEFAULT_NUMBER_OF_SIGNATURES,
  DEFAULT_SIGNATURE_BYTE_SIZE,
  STAKE_AMOUNT_STEP,
};
