export const chartStyles = {
  borderColor: { dark: '#4d4d50', light: '#e1e3eb' },
  backgroundColor: { dark: '#111112', light: '#ffffff' },
  titleColor: { dark: '#ffffff', light: '#0c152e' },
  textColor: { dark: '#70778b', light: '#70778b' },
  pointBackgroundColor: { dark: 'rgba(28, 28, 30, 0.8)', light: '#ffffff' },
  whiteColor: '#ffffff',
  platinumColor: '#e1e3eb',
  slateGray: '#70778b',
  maastrichtBlue: '#0c152e',
  ultramarineBlue: '#4070f4',
  darkBlue: '#254898',
  ufoGreen: '#2bd67b',
  linthPink: '#f8d2d2',
  pasterPink: '#FBD0D1',
  mystic: '#edf0f5',
  warningBorder: '#f7e36d',
  cobaltBlue: '#254798',
  burntSienna: '#ec6868',
  orange: '#ff7721',
  rainbowEnd: '#35f2b6',
  transparent: 'rgba(0, 0, 0, 0)',
  contentFontFamily: "'basier-circle', sans-serif",
  fontSize: 13,
};

export const colorPalette = [
  chartStyles.ufoGreen,
  chartStyles.ultramarineBlue,
  chartStyles.maastrichtBlue,
  chartStyles.linthPink,
  chartStyles.darkBlue,
  chartStyles.slateGray,
  chartStyles.burntSienna,
  chartStyles.orange,
  chartStyles.rainbowEnd,
];

export const colorPaletteDark = [
  chartStyles.ufoGreen,
  chartStyles.ultramarineBlue,
  chartStyles.warningBorder,
  chartStyles.pasterPink,
  chartStyles.cobaltBlue,
  chartStyles.slateGray,
  chartStyles.burntSienna,
  chartStyles.orange,
  chartStyles.rainbowEnd,
];
