const actionTypes = {
  metronomeBeat: 'METRONOME_BEAT',
  accountUpdated: 'ACCOUNT_UPDATED',
  accountLoggedOut: 'ACCOUNT_LOGGED_OUT',
  accountLoggedIn: 'ACCOUNT_LOGGED_IN',
  activePeerSet: 'ACTIVE_PEER_SET',
  activePeerUpdate: 'ACTIVE_PEER_UPDATE',
  activePeerReset: 'ACTIVE_PEER_RESET',
  dialogDisplayed: 'DIALOG_DISPLAYED',
  dialogHidden: 'DIALOG_HIDDEN',
  forgedBlocksUpdated: 'FORGED_BLOCKS_UPDATED',
  forgingStatsUpdated: 'FORGING_STATS_UPDATED',
  forgingReset: 'FORGING_RESET',
  VotePlaced: 'VOTE_PLACED',
  addedToVoteList: 'ADDED_TO_VOTE_LIST',
  removedFromVoteList: 'REMOVEd_FROM_VOTE_LIST',
  votesCleared: 'VOTES_CLEARED',
  pendingVotesAdded: 'PENDING_VOTES_ADDED',
  toastDisplayed: 'TOAST_DISPLAYED',
  toastHidden: 'TOAST_HIDDEN',
  loadingStarted: 'LOADING_STARTED',
  loadingFinished: 'LOADING_FINISHED',
  transactionAdded: 'TRANSACTION_ADDED',
  transactionsUpdated: 'TRANSACTIONS_UPDATED',
  transactionsLoaded: 'TRANSACTIONS_LOADED',
  transactionsReset: 'TRANSACTIONS_RESET',
};

export default actionTypes;
