const links = {
  accountInitialization: 'https://lisk.io/help-center/account-security/should-i-initialize-my-lisk-account',
  blockchainTransparencyExplained: 'https://lisk.io/academy/blockchain-basics/benefits-of-blockchain/blockchain-transparency-explained',
  discord: 'https://discord.gg/CngsY6D',
  explainBlockchain: 'https://lisk.io/academy/blockchain-basics/what-is-blockchain/eli5-blockchain',
  gettingStarted: 'https://lisk.io/academy/welcome-to-the-lisk-academy/getting-started-with-lisk',
  helpCenter: 'https://lisk.io/help-center',
  helpDeskChannel: 'https://lisk.chat/channel/help-desk',
  howToStorePassphrase: 'https://lisk.io/academy/blockchain-business/cryptocurrencies/how-to-stay-secure-when-trading-cryptocurrencies',
  isBlockchainSecure: 'https://lisk.io/academy/blockchain-basics/benefits-of-blockchain/blockchain-security',
  ledgerNanoSHelp: 'https://support.ledger.com/hc/en-us/categories/115000820045-Ledger-Nano-S',
  liskAcademy: 'https://lisk.io/academy',
  liskChat: 'https://lisk.chat/home',
  outgoingTransactions: 'https://lisk.io/help-center/transactions/how-to-make-an-outgoing-lsk-transaction',
  privacyPolicy: 'https://lisk.io/privacy',
  seeMore: 'https://lisk.io/academy/blockchain-basics/how-does-blockchain-work',
  sidechains: 'https://lisk.io/help-center/dapp-development/what-are-sidechains',
  transactionFee: 'https://lisk.io/help-center/getting-started/does-lisk-have-transaction-fees',
  trezorOneHelp: 'https://wiki.trezor.io/PIN',
  votingAndDelegates: 'https://lisk.io/help-center#voting-and-delegates',
  votingOnLisk: 'https://lisk.io/academy/welcome-to-the-lisk-academy/getting-started-with-lisk/voting-on-lisk',
  whatIsAnPassphrase: 'https://lisk.io/help-center/account-security/what-is-a-lisk-passphrase',
};
export default links;
