
export default {
  URL: 'matomo.lisk.io/',
  SITE_ID: 1,
  DELETE_CUSTOM_VARIABLE: 'deleteCustomVariable',
  ENABLE_HEART_BEAT_TIMER: 'enableHeartBeatTimer',
  ENABLE_LINK_TRACKING: 'enableLinkTracking',
  FORGET_CONSENT_GIVEN: 'forgetConsentGiven',
  OPTIONAL_EXPIRE_CONSENT_IN_HOURS: 'optionallyExpireConsentInHours',
  REMEMBER_CONSENT_GIVEN: 'rememberConsentGiven',
  REQUIRE_CONSENT: 'requireConsent',
  RESET_USER_ID: 'resetUserId',
  SET_CUSTOM_URL: 'setCustomUrl',
  SET_CUSTOM_VARIABLE: 'setCustomVariable',
  SET_DOCUMENT_TITLE: 'setDocumentTitle',
  SET_GENERATATION_TIME_MS: 'setGenerationTimeMs',
  SET_REFERRER_URL: 'setReferrerUrl',
  SET_SITE_ID: 'setSiteId',
  SET_TRACKER_URL: 'setTrackerUrl',
  SET_USER_ID: 'setUserId',
  TRACK_ALL_CONTENT_IMPRESSIONS: 'trackAllContentImpressions',
  TRACK_ERRORS: 'trackErrors',
  TRACK_PAGE_VIEW: 'trackPageView',
};
