export default {
  wallet: { url: '/transactions' },
  account: { url: '/accounts' },
  accountVisualDemo: { url: '/account-visual-demo' },
  dashboard: { url: '/dashboard' },
  search: { url: '/search' },
  searchResult: { url: '/result' },
  transaction: { url: '/transactions' },
  login: { url: '/' },
  addAccount: { url: '/add-account' },
  register: { url: '/register' },
  sidechains: { url: '/sidechains' },
  voting: { url: '/voting' },
  main: '/main',
  explorer: '/explorer',
};
