export default {
  wallet: { path: '/wallet' },
  account: { path: '/accounts' },
  accountVisualDemo: { path: '/account-visual-demo' },
  dashboard: { path: '/dashboard' },
  search: { path: '/search' },
  searchResult: { path: '/result' },
  login: { path: '/' },
  accounts: { path: '/accounts' },
  addAccount: { path: '/add-account' },
  register: { path: '/register' },
  sidechains: { path: '/sidechains' },
  delegates: { path: '/delegates' },
  explorer: { path: '/explorer' },
  secondPassphrase: { path: '/second-passphrase' },
};
