import React from 'react';
import { render, screen } from '@testing-library/react';
import TableLoadingState from './index';

describe('TableLoadingState', () => {
  const props = {
    count: 5,
    header: [
      {
        title: 'Height',
        classList: 'col-xs-3',
      },
      {
        title: 'Date',
        classList: 'col-xs-3',
      },
      {
        title: 'Generated by',
        classList: 'col-xs-3',
      },
      {
        title: 'Transactions',
        classList: 'col-xs-2',
      },
      {
        title: 'Generated',
        classList: 'col-xs-1',
      },
    ],
    isFetching: true,
  };
  it('renders a blocks skeleton row skeleton', () => {
    render(<TableLoadingState {...props} />);
    expect(screen.getAllByTestId('skeleton-row')).toHaveLength(5);
  });
});
