import PropTypes from 'prop-types';
import React, { useState } from 'react';
import { useTranslation } from 'react-i18next';
import Box from 'src/theme/box';
import BoxContent from 'src/theme/box/content';
import FilterBar from 'src/modules/common/components/filterBar';
import StickyHeader from 'src/theme/table/stickyHeader';
import Table from 'src/theme/table';
import transformParams from 'src/utils/transformParams';
import { useBlocks } from '../../hooks/queries/useBlocks';
import BlocksOverview from '../blocksOverview';
import BlockFilterDropdown from './blockFilterDropdown';
import BlockRow from './blockRow';
import header from './tableHeader';
import styles from './blocks.css';

export const defaultFilters = {
  dateFrom: '',
  dateTo: '',
  height: '',
  generatorAddress: '',
};

// eslint-disable-next-line max-statements
const Blocks = ({
  filters,
  applyFilters,
  clearFilter,
  clearAllFilters,
  sort,
  changeSort,
}) => {
  const { t } = useTranslation();
  const [config, setConfig] = useState({ params: {} });
  const {
    data: blocks, error, isFetching, fetchNextPage, hasNextPage,
  } = useBlocks({ config });

  const formatters = {
    height: (value) => `${t('Height')}: ${value}`,
    /* istanbul ignore next */
    generatorAddress: (value) => `${t('Generated by')}: ${value}`,
  };

  const handleLoadMore = () => {
    const searchParams = Object.keys(filters).reduce(
      (acc, key) => ({
        ...acc,
        ...(filters[key] && { [key]: filters[key] }),
      }),
      {
        offset: blocks.data.length,
        sort,
      },
    );
    fetchNextPage({ pageParam: transformParams(searchParams) });
  };

  const applyBlockFilters = (blockFilters) => {
    console.log('+++', blockFilters);
    const updateApplyFilterData = (usedFilters) =>
      setConfig({ params: transformParams(usedFilters) });
    applyFilters(blockFilters, null, updateApplyFilterData);
  };

  const clearBlockFilter = (name) => {
    const filterData = {
      ...filters,
      [name]: defaultFilters[name],
    };
    const updateFilterData = () => setConfig({ params: transformParams(filterData) });
    clearFilter(name, updateFilterData);
  };

  const clearAllBlockFilters = () => {
    const clearFilterData = () => setConfig({ params: {} });
    clearAllFilters(clearFilterData);
  };

  const changeBlockSort = (id) => {
    const sortData = {
      ...filters,
      sort: `${id}:${sort.includes('asc') ? 'desc' : 'asc'}`,
    };
    const updateSort = () => setConfig({ params: transformParams(sortData) });
    changeSort(id, updateSort);
  };

  /* istanbul ignore next */
  const loadLastBlocks = () => {
    applyBlockFilters(filters);
  };

  return (
    <div>
      <BlocksOverview t={t} />
      <Box
        isLoading={isFetching}
        className="blocks-container"
        width="full"
        main
      >
        <StickyHeader
          title={t('All blocks')}
          button={{
            entity: 'block',
            error,
            onClick: loadLastBlocks,
            label: t('New blocks'),
          }}
          scrollToSelector=".blocks-container"
          filters={(
            <BlockFilterDropdown
              filters={filters}
              applyFilters={applyBlockFilters}
            />
          )}
        />
        <FilterBar
          {...{
            clearFilter: clearBlockFilter,
            clearAllFilters: clearAllBlockFilters,
            filters,
            formatters,
            t,
          }}
        />
        <BoxContent className={`${styles.content} block-results`}>
          <Table
            showHeader
            data={blocks?.data ?? []}
            isLoading={isFetching}
            row={BlockRow}
            loadData={handleLoadMore}
            header={header(changeBlockSort, t)}
            headerClassName={styles.tableHeader}
            currentSort={sort}
            canLoadMore={hasNextPage}
            error={error}
          />
        </BoxContent>
      </Box>
    </div>
  );
};

Blocks.propTypes = {
  filters: PropTypes.shape({
    dateFrom: PropTypes.string.isRequired,
    dateTo: PropTypes.string.isRequired,
    height: PropTypes.string.isRequired,
    generatorAddress: PropTypes.string.isRequired,
  }).isRequired,
};

export default Blocks;
