import React from 'react';
import { MODULE_COMMANDS_NAME_MAP } from '@transaction/configuration/moduleCommand';
import Box from '@theme/box';
import BoxHeader from '@theme/box/header';
import { TertiaryButton } from '@theme/buttons';
import BoxContent from '@theme/box/content';
import Illustration from '@common/components/illustration';
import Tooltip from '@theme/Tooltip';
import { tokenMap } from '@token/fungible/consts/tokens';
import Icon from '@theme/Icon';
import useNonceSync from '@auth/hooks/useNonceSync';
import TransactionInfo from '../TransactionInfo';
import Footer from './footer';
import styles from './txSummarizer.css';
import FeeSummarizer from './FeeSummarizer';

// eslint-disable-next-line complexity
const TxSummarizer = ({
  title,
  children,
  confirmButton,
  cancelButton,
  wallet,
  width = 'medium',
  t,
  className,
  token,
  footerClassName,
  formProps,
  transactionJSON,
  summaryInfo,
  selectedPriority,
  hasCancel,
  hasNoTopCancelButton,
  noFeeStatus,
}) => {
  const { onChainNonce } = useNonceSync();
  const isTransactionAuthor = transactionJSON.senderPublicKey === wallet.summary.publicKey;
  const isNonceEqual = transactionJSON.nonce === onChainNonce;
  const nonceWarning = isTransactionAuthor && !isNonceEqual;
  const fee = !(
    wallet.summary.isMultisignature ||
    formProps.moduleCommand === MODULE_COMMANDS_NAME_MAP.registerMultisignature
  )
    ? transactionJSON.fee
    : 0;

  const tooltip = {
    title: t('Transaction fee'),
    children: t(
      'Transaction fees are required for every transaction to be accepted and generated by the {{network}} network. When the network is busy, transactions with a higher fee are confirmed sooner.',
      { network: tokenMap[token].label }
    ),
  };

  return (
    <Box width={width} className={`${styles.wrapper} ${className} summary`}>
      {title && (
        <BoxHeader className={`${styles.header} summary-header`}>
          {!hasNoTopCancelButton ? (
            <TertiaryButton className="cancel-button" onClick={cancelButton.onClick}>
              <Icon name="arrowLeftTailed" />
            </TertiaryButton>
          ) : null}
          &nbsp;&nbsp;&nbsp;
          <h2>{title}</h2>
        </BoxHeader>
      )}
      <BoxContent className={`${styles.content} summary-content`}>
        {wallet.loginType ? (
          <Illustration
            name={wallet.loginType}
            className={`${styles.illustrationWrapper} illustration`}
          />
        ) : null}
        {children}
        <TransactionInfo
          token={token}
          summaryInfo={summaryInfo}
          formProps={formProps}
          transactionJSON={transactionJSON}
          account={wallet}
          isMultisignature={wallet.summary.isMultisignature}
          nonceWarning={nonceWarning}
        />
        {!noFeeStatus && !!fee && (
          <section>
            <div className={styles.feesWrapper}>
              <div>
                <label>
                  {t('Priority')}
                  <Tooltip title={tooltip.title} footer={tooltip.footer} position="right">
                    <p className={styles.tooltipText}>{tooltip.children}</p>
                  </Tooltip>
                </label>
                <div>{selectedPriority.title}</div>
              </div>
              <div>
                <label>
                  {t('Fees')}
                  <Tooltip title={tooltip.title} footer={tooltip.footer} position="top">
                    <p className={styles.tooltipText}>{tooltip.children}</p>
                  </Tooltip>
                </label>
                <FeeSummarizer fees={formProps.composedFees} />
              </div>
            </div>
          </section>
        )}
        {nonceWarning && (
          <div className={styles.nonceWarning}>
            <Icon name="warningYellow" />
            <p>
              {t(
                'Please ensure to send the previously initiated transactions. Check the transaction sequence, and broadcast them only after they have been fully signed, in their original order.'
              )}
            </p>
          </div>
        )}
      </BoxContent>
      <Footer
        cancelButton={hasCancel && cancelButton}
        confirmButton={confirmButton}
        footerClassName={footerClassName}
        t={t}
        account={wallet}
      />
    </Box>
  );
};

export default TxSummarizer;
