export const RESPONSE = 'RESPONSE';
export const REQUEST = 'REQUEST';
export const LEDGER_HW_HID_EVENT = 'LEDGER_HW_HID_EVENT';
export const LEDGER_HW_IPC_CHANNELS = {
  GET_SIGNED_MESSAGE: 'GET_SIGNED_MESSAGE',
  GET_SIGNED_TRANSACTION: 'GET_SIGNED_TRANSACTION',
  GET_PUB_KEY: 'GET_PUB_KEY',
  RESET_LEDGER_IPC_QUEUE: 'RESET_LEDGER_IPC_QUEUE',
  GET_CONNECTED_DEVICES: 'GET_CONNECTED_DEVICES',
};
