export { default as wallet } from '@wallet/store/reducers/reducer';
export { default as bookmarks } from '@bookmark/store/reducer';
export { default as settings } from 'src/modules/settings/store/reducer';
export { default as token } from '@token/fungible/store/reducer';
export { default as transactions } from '@transaction/store/reducer';
export { default as appUpdates } from '@update/store/reducers/appUpdates';
export { default as staking } from '@pos/validator/store/reducers/staking';
export { hardwareWallet } from '@hardwareWallet/store/reducers';
export { default as watchList } from '@pos/validator/store/reducers/watchList';
export { account } from '@account/store/reducer';
export { blockChainApplications } from '@blockchainApplication/manage/store/reducer';
export { default as service } from '@wallet/store/reducers/service';
export { default as loading } from 'src/modules/common/store/reducers/loading';
