import React from 'react';
import styles from './flag.css';

const codes = {
  dz: 'algeria',
  am: 'armenia',
  at: 'austria',
  az: 'azerbaijan',
  bs: 'bahamas',
  bh: 'bahrain',
  bd: 'bangladesh',
  bb: 'barbados',
  be: 'belgium',
  bj: 'benin',
  bo: 'bolivia',
  bw: 'botswana',
  br: 'brazil',
  bg: 'bulgaria',
  bf: 'burkina faso',
  bi: 'burundi',
  cm: 'cameroon',
  gb: 'the-united-kingdom',
  td: 'chad',
  cl: 'chile',
  co: 'colombia',
  km: 'comoros',
  cu: 'cuba',
  dk: 'denmark',
  dj: 'djibouti',
  ee: 'estonia',
  fi: 'finland',
  fr: 'france',
  ga: 'gabon',
  de: 'germany',
  gh: 'ghana',
  gr: 'greece',
  gn: 'guinea',
  gw: 'guinea-bissau',
  gy: 'guyana',
  hu: 'hungary',
  is: 'iceland',
  in: 'india',
  id: 'indonesia',
  iq: 'iraq',
  ie: 'ireland',
  il: 'israel',
  it: 'italy',
  jm: 'jamaica',
  jp: 'japan',
  kw: 'kuwait',
  lv: 'latvia',
  lr: 'liberia',
  ly: 'libya',
  lt: 'lithuania',
  lu: 'luxembourg',
  mg: 'madagascar',
  my: 'malaysia',
  mv: 'maldives',
  ml: 'mali',
  mr: 'mauritania',
  mu: 'mauritius',
  mc: 'monaco',
  mm: 'myanmar',
  na: 'namibia',
  nr: 'nauru',
  np: 'nepal',
  ne: 'niger',
  ng: 'nigeria',
  nl: 'the-netherlands',
  no: 'norway',
  pk: 'pakistan',
  pw: 'palau',
  pa: 'panama',
  pe: 'peru',
  pl: 'poland',
  qa: 'qatar',
  ro: 'romania',
  rw: 'rwanda',
  sn: 'senegal',
  sc: 'seychelles',
  so: 'somalia',
  sd: 'sudan',
  sr: 'suriname',
  se: 'sweden',
  ch: 'switzerland',
  th: 'thailand',
  tg: 'togo',
  to: 'tonga',
  tn: 'tunisia',
  tr: 'turkey',
  ua: 'ukraine',
  ye: 'yemen',
  us: 'the-united-states',
};

const Flag = ({ code }) => {
  const flagStyle = code && styles[codes[code.toLowerCase()]];
  return (
    <div className={`${styles.flag} ${flagStyle ? styles.bordered : null}`}>
      {
        flagStyle
          ? <span className={`${styles.sprite} ${flagStyle}`} />
          : '-'
      }
    </div>
  );
};

export default Flag;
