export const unitTestsDict = [
  './utils/savedAccounts.test.js',
  './utils/localJSONStorage.test.js',
  './utils/ipcLocale.test.js',
  './utils/passphrase.test.js',
  './utils/notification.test.js',
  './utils/delegates.test.js',
  './utils/account.test.js',
  './utils/followedAccounts.test.js',
  './utils/polyfills.test.js',
  './utils/lsk.test.js',
  './utils/externalLinks.test.js',
  './utils/app.test.js',
  './utils/similarWord.test.js',
  './utils/api/search.test.js',
  './utils/api/account.test.js',
  './utils/api/transactions.test.js',
  './utils/api/peers.test.js',
  './utils/api/nethash.test.js',
  './utils/api/delegate.test.js',
  './utils/generateUniqueId.test.js',
  './utils/login.test.js',
  './components/searchBar/index.test.js',
  './components/accountTransactions/index.test.js',
  './components/multiStep/index.test.js',
  './components/multiStep/multiStepNav.test.js',
  './components/fontIcon/index.test.js',
  './components/toaster/toaster.test.js',
  './components/toaster/index.test.js',
  './components/votesPreview/votesPreview.test.js',
  './components/accountVisual/index.test.js',
  './components/sendReadable/index.test.js',
  './components/sendReadable/send.test.js',
  './components/savedAccounts/savedAccounts.test.js',
  './components/savedAccounts/accountCard.test.js',
  './components/savedAccounts/index.test.js',
  './components/box/index.test.js',
  './components/app/index.test.js',
  './components/secondPassphrase/index.test.js',
  './components/secondPassphrase/secondPassphrase.test.js',
  './components/errorBoundary/index.test.js',
  './components/menuBar/menuBar.test.js',
  './components/converter/converter.test.js',
  './components/converter/index.test.js',
  './components/notFound/index.test.js',
  './components/authenticate/authenticate.test.js',
  './components/authenticate/index.test.js',
  './components/autoSuggest/index.test.js',
  './components/followedAccounts/addAccountTitle.test.js',
  './components/followedAccounts/viewAccounts.test.js',
  './components/followedAccounts/addAccountID.test.js',
  './components/voting/voting.test.js',
  './components/voting/index.test.js',
  './components/customRoute/index.test.js',
  './components/passphrase/ConfirmSecond/index.test.js',
  './components/passphrase/ConfirmSecond/confirmSecond.test.js',
  './components/passphrase/safekeeping/index.test.js',
  './components/passphrase/confirm/index.test.js',
  './components/passphrase/confirm/form.test.js',
  './components/passphrase/info/index.test.js',
  './components/passphrase/createSecond/create.test.js',
  './components/passphrase/create/movableShape.test.js',
  './components/passphrase/create/create.test.js',
  './components/sendTo/followAccount.test.js',
  './components/sendTo/sendTo.test.js',
  './components/sidechains/index.test.js',
  './components/spinner/index.test.js',
  './components/parallax/index.test.js',
  './components/confirmVotes/confirmVotes.test.js',
  './components/confirmVotes/index.test.js',
  './components/passphraseInput/index.test.js',
  './components/search/keyAction.test.js',
  './components/search/searchResult.test.js',
  './components/dialog/alert.test.js',
  './components/dialog/dialog.test.js',
  './components/dashboard/currencyGraph.test.js',
  './components/liskAmount/index.test.js',
  './components/registerDelegate/index.test.js',
  './components/registerDelegate/steps/choose/choose.test.js',
  './components/registerDelegate/steps/confirm/confirm.test.js',
  './components/registerDelegate/registerDelegate.test.js',
  './components/transactions/amount.test.js',
  './components/transactions/transactionRow.test.js',
  './components/transactions/transactionType.test.js',
  './components/transactions/explorerTransactions/index.test.js',
  './components/transactions/transactionList.test.js',
  './components/transactions/transactionOverview.test.js',
  './components/transactions/transactionsHeader.test.js',
  './components/transactions/walletTransactions/index.test.js',
  './components/transactions/transactionDetailView.test.js',
  './components/transactions/delegateStatistics.test.js',
  './components/transactions/status.test.js',
  './components/register/index.test.js',
  './components/register/register.test.js',
  './components/pricedButton/index.test.js',
  './components/copyToClipboard/index.test.js',
  './components/loadingBar/index.test.js',
  './components/loadingBar/loadingBar.test.js',
  './components/toolbox/buttons/button.test.js',
  './components/toolbox/buttons/iconButton.test.js',
  './components/toolbox/sliderCheckbox/index.test.js',
  './components/toolbox/transitionWrapper/index.test.js',
  './components/request/specifyRequest.test.js',
  './components/request/confirmRequest.test.js',
  './components/sendWritable/index.test.js',
  './components/sendWritable/send.test.js',
  './components/actionBar/index.test.js',
  './components/mainMenu/mainMenu.test.js',
  './components/mainMenu/index.test.js',
  './components/resultBox/resultBox.test.js',
  './components/proxyDialog/index.test.js',
  './components/passphraseCreation/index.test.js',
  './components/authInputs/authInputs.test.js',
  './components/authInputs/index.test.js',
  './components/account/account.test.js',
  './components/account/index.test.js',
  './components/setting/index.test.js',
  './components/setting/setting.test.js',
  './components/timestamp/index.test.js',
  './components/send/index.test.js',
  './components/votingListView/voteRow.test.js',
  './components/votingListView/delegateRow.test.js',
  './components/votingListView/votingListView.test.js',
  './components/votingListView/delegateList.test.js',
  './components/votingListView/index.test.js',
  './components/votingListView/voteCheckbox.test.js',
  './components/votingListView/votingHeader.test.js',
  './components/offlineWrapper/index.test.js',
  './components/formattedNumber/index.test.js',
  './components/voteUrlProcessor/index.test.js',
  './components/voteUrlProcessor/voteUrlProcessor.test.js',
  './components/login/index.test.js',
  './components/login/login.test.js',
  './components/header/countDownTemplate.test.js',
  './components/header/index.test.js',
  './components/header/customCountDown.test.js',
  './components/header/header.test.js',
  './components/signMessage/signMessage.test.js',
  './components/onboarding/onboarding.test.js',
  './components/privateWrapper/index.test.js',
  // './actions/savedAccounts.test.js',
  './actions/toaster.test.js',
  './actions/dialog.test.js',
  './actions/voting.test.js',
  './actions/account.test.js',
  // './actions/loding.test.js',
  './actions/followedAccounts.test.js',
  './actions/transactions.test.js',
  // './actions/peers.test.js',
  './actions/delegate.test.js',
  // './actions/setting.test.js',
  './store/middlewares/savedAccounts.test.js',
  // './store/middlewares/socket.test.js',
  // './store/middlewares/savedSettings.test.js',
  './store/middlewares/offline.test.js',
  './store/middlewares/notification.test.js',
  // './store/middlewares/voting.test.js',
  './store/middlewares/account.test.js',
  './store/middlewares/followedAccounts.test.js',
  './store/middlewares/peers.test.js',
  './store/middlewares/loadingBar.test.js',
  './store/middlewares/login.test.js',
  './store/subscribers/savedAccounts.test.js',
  './store/subscribers/followedAccounts.test.js',
  './store/reducers/search.test.js',
  './store/reducers/savedAccounts.test.js',
  './store/reducers/dialog.test.js',
  // './store/reducers/voting.test.js',
  './store/reducers/account.test.js',
  './store/reducers/loding.test.js',
  './store/reducers/followedAccounts.test.js',
  // './store/reducers/transactions.test.js',
  './store/reducers/peers.test.js',
  // './store/reducers/toater.test.js',
  // './store/reducers/settings.test.js',
  './store/reducers/delegate.test.js',
  // './store/reducers/transaction.test.js',
];

export const integrationTestsDict = [
  './accountSwitch.test.js',
  './accountTransactions.test.js',
  './dashboard.test.js',
  // './login.test.js',
  // './register.test.js',
  // './registerDelegate.test.js',
  // './transactionID.test.js',
  // './voting.test.js',
  './wallet.test.js',
];
