const urls = {
  dashboard: '/dashboard',
  wallet: '/wallet?tab=Transactions',
  wallets: '/wallets',
  send: '/wallet?modal=send',
  request: '/wallet/request',
  help: '/help',
  settings: '/settings',
  account: '/account',
  accounts: '/accounts',
  transactions: '/transactions',
  register: '/register',
  secondPassphrase: '/second-passphrase',
  registerDelegate: '/register-delegate',
  delegates: '/delegates',
  voting: '/voting',
  delegatesVote: '/delegates/vote',
  signMessage: '/sign-message',
  login: '/login',
  network: '/network',
  blocks: '/blocks',
  explorer: '/explorer',
};

export default urls;
