const urls = {
  wallet: '/wallet?tab=Transactions',
  wallets: '/wallets',
  send: '/wallet?modal=send',
  request: '/wallet/request',
  help: '/help',
  settings: '/settings',
  account: '/account',
  accounts: '/accounts',
  transactions: '/transactions',
  register: '/register',
  secondPassphrase: '/second-passphrase',
  registerValidator: '/register-validator',
  validators: '/validators',
  staking: '/staking',
  validatorsStake: '/validators/stake',
  signMessage: '/sign-message',
  login: '/login',
  network: '/network',
  blocks: '/blocks',
  explorer: '/explorer',
  applications: '/applications',
  mangedApplications: '/wallet?modal=manageApplications',
};

export default urls;
